# Generated by Django 4.0 on 2021-12-30 13:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AtriTell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='random_url_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
