# Generated by Django 4.0.5 on 2022-07-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtriTell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_user_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_auth_token',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
