# Generated by Django 4.0.1 on 2022-01-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtriTell', '0003_delete_article_note_author_note_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
