# Generated by Django 4.0.5 on 2022-06-23 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtriTell', '0005_post_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateField(default=datetime.date(2022, 6, 23)),
        ),
    ]
