# Generated by Django 4.0.5 on 2022-06-23 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AtriTell', '0006_alter_post_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 23, 15, 6, 50, 874197, tzinfo=utc)),
        ),
    ]
