# Generated by Django 4.0.5 on 2022-06-23 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AtriTell', '0007_alter_post_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 15, 7, 59, 643558, tzinfo=utc)),
        ),
    ]
